name: home_widget
description: A plugin to provide a common interface for creating HomeScreen Widgets for Android and iOS.
version: 0.5.0
repository: https://github.com/ABausG/home_widget

environment:
  sdk: '>=3.4.0-99.1.beta <4.0.0'
  flutter: ">=3.20.0-1.2"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  path_provider_foundation: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.1
  path_provider_platform_interface:
  plugin_platform_interface:

flutter:
  plugin:
    platforms:
      android:
        package: es.antonborri.home_widget
        pluginClass: HomeWidgetPlugin
      ios:
        pluginClass: HomeWidgetPlugin
